name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t cypress-tests .

      - name: Run stable tests in Docker
        run: docker run cypress-tests --spec "cypress/e2e/{api,search,sidebar}/**/*.cy.ts"
  future-tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run future feature tests
        run: npx cypress run --spec "cypress/e2e/{dashboard,language}/**/*.cy.ts"  